"""
fetch_data.py — Tasi Terminal (مشروع مستقل بالكامل)
المرحلة 3: تغطية كاملة — كل قطاعات السوق السعودي (270 سهم) وكل شركات S&P 500 الأمريكية (503 سهم).
الرموز موثّقة من مصادر رسمية علنية (stockanalysis.com للسعودي، Wikipedia GICS للأمريكي).

يكتب النتيجة الموحّدة إلى data/data.json
"""

import json
import os
import math
import datetime
import numpy as np
import pandas as pd
import yfinance as yf

SECTORS = {
    "sa": {
        "label": "السوق السعودي",
        "currency": "ر.س",
        "sectors": {
            "الطاقة": {
                "2222.SR": "أرامكو السعودية",
                "2381.SR": "Arabian Drilling Company",
            },
            "البنوك": {
                "1120.SR": "مصرف الراجحي",
                "1180.SR": "البنك الأهلي السعودي",
                "1010.SR": "بنك الرياض",
                "1150.SR": "مصرف الإنماء",
                "1060.SR": "البنك السعودي الأول",
                "1050.SR": "البنك السعودي الفرنسي",
                "1080.SR": "البنك العربي الوطني",
                "1140.SR": "بنك البلاد",
                "1030.SR": "البنك السعودي للاستثمار",
                "1020.SR": "بنك الجزيرة",
            },
            "التعدين": {
                "1211.SR": "معادن",
                "1322.SR": "Al Masane Al Kobra Mining Company",
                "9583.SR": "United Mining Industries Company",
            },
            "الاتصالات": {
                "7010.SR": "الاتصالات السعودية",
                "7020.SR": "موبايلي",
                "4142.SR": "Riyadh Cables Group Company",
                "7030.SR": "زين السعودية",
                "7040.SR": "اتحاد اتصالات (موبايلي)",
                "2370.SR": "Middle East Specialized Cables Company",
                "2110.SR": "Saudi Cable Company",
            },
            "الصناعة": {
                "2010.SR": "سابك",
                "1303.SR": "الصناعات الكهربائية",
                "1212.SR": "Astra Industrial Group Company",
                "2250.SR": "المجموعة السعودية للصناعات الأساسية (سابك للاستثمارات)",
                "1321.SR": "East Pipes Integrated Company for Industry",
                "2230.SR": "Saudi Chemical Holding Company",
                "2060.SR": "التصنيع",
                "4071.SR": "Arabian Contracting Services Company",
                "1320.SR": "Saudi Steel Pipes Company",
                "2040.SR": "Saudi Ceramic Company",
                "1302.SR": "بوان",
                "1304.SR": "Al Yamamah Steel Industries Company",
                "2300.SR": "Saudi Paper Manufacturing Company",
                "2240.SR": "Advanced Building Industries Co.",
                "9523.SR": "Group Five Pipe Saudi Company",
                "1202.SR": "Middle East Company for Manufacturing and Producing Paper",
                "2200.SR": "Arabian Pipes Company",
                "4143.SR": "Al Taiseer Group TALCO Industrial Company",
                "2150.SR": "The National Company for Glass Industries",
                "4230.SR": "Red Sea International Company",
                "1323.SR": "United Carton Industries Company",
                "2120.SR": "Saudi Advanced Industries Company",
                "2340.SR": "Artex Industrial Investment Company",
                "4145.SR": "Al Obeikan Glass Company",
                "4148.SR": "Alwasail Industrial Company",
                "1210.SR": "Basic Chemical Industries Company",
                "2160.SR": "The Saudi Arabian Amiantit Company",
                "9611.SR": "Arabian United Float Glass Company",
                "9575.SR": "Marble Design Factory Company",
                "9517.SR": "MOBI Industry Co.",
                "1301.SR": "United Wire Factories Company",
                "4140.SR": "Saudi Industrial Export Company",
                "2090.SR": "National Gypsum Company",
                "2210.SR": "Nama Chemicals Company",
                "2220.SR": "National Metal Manufacturing and Casting Co.",
                "1201.SR": "Takween Advanced Industries",
                "2180.SR": "Filling and Packing Materials Manufacturing Company",
                "9580.SR": "Al Rashid Industrial Co.,",
            },
            "المرافق": {
                "2082.SR": "أكوا باور",
                "5110.SR": "السعودية للكهرباء",
                "2083.SR": "Power and Water Utility Company for Jubail and Yanbu",
                "2080.SR": "National Gas and Industrialization Company",
                "2320.SR": "Al-Babtain Power and Telecommunications Company",
                "2081.SR": "Alkhorayef Water and Power Technologies Company",
                "1834.SR": "Saudi Manpower Solutions Company",
                "4146.SR": "Gas Arabian Services Company",
                "2084.SR": "Miahona Company Limited",
                "1833.SR": "Almawarid Manpower Company",
                "2282.SR": "Naqi Water Company",
            },
            "الرعاية الصحية والأدوية": {
                "4013.SR": "د. سليمان الحبيب",
                "4002.SR": "المواساة",
                "4164.SR": "صيدليات النهدي",
                "4004.SR": "دله الصحية",
                "4015.SR": "Jamjoom Pharmaceuticals Factory Company",
                "4017.SR": "Dr. Soliman Abdel Kader Fakeeh Hospital Company",
                "4018.SR": "Almoosa Health Company",
                "4005.SR": "National Medical Care Company",
                "4019.SR": "Specialized Medical Company",
                "4163.SR": "Al-Dawaa Medical Services Company",
                "2070.SR": "الصناعات الدوائية",
                "4009.SR": "Middle East Healthcare Company",
                "4016.SR": "Middle East Pharmaceutical Industries Company",
                "4014.SR": "Scientific and Medical Equipment House Company",
                "9544.SR": "Future Care Trading Co.",
                "9527.SR": "Alf Meem Yaa for Medical Supplies and Equipment Company",
                "9546.SR": "Naba Al Saha Medical Services Company",
                "4021.SR": "Canadian General Medical Center Complex Company",
                "9530.SR": "Arabian International Healthcare Holding Company",
                "9627.SR": "Twareat Medical Care Company",
            },
            "البتروكيماويات": {
                "2020.SR": "سافكو",
                "2380.SR": "رابغ للتكرير والبتروكيماويات",
                "2223.SR": "لوبريف",
                "2290.SR": "ينساب",
                "2310.SR": "سابك للمغذيات الزراعية",
                "2350.SR": "كيان السعودية",
                "2330.SR": "المتقدمة",
                "2170.SR": "Alujain Corporation",
                "2030.SR": "Saudi Arabian Refineries Company",
                "2001.SR": "Methanol Chemicals Company",
            },
            "البرمجيات والتقنية": {
                "7203.SR": "علم",
                "7202.SR": "Arabian Internet and Communication Services Company",
                "8313.SR": "Rasan Information Technology Company",
                "7200.SR": "Al Moammar Information Systems Company",
                "6017.SR": "Jahez International Company for Information Systems Technology",
                "9557.SR": "Edarat Communication and Information Technology Co.",
                "7211.SR": "Saudi Azm for Communication and Information Technology Company",
                "9637.SR": "Axelerated Solutions for Information and Communication Technology Company | 728.00M",
            },
            "الأغذية": {
                "2280.SR": "المراعي",
                "6015.SR": "أمريكانا",
                "2050.SR": "صافولا",
                "2270.SR": "سدافكو",
                "4162.SR": "Almunajem Foods Company",
                "2283.SR": "The First Milling Company",
                "2285.SR": "Arabian Mills for Food Products Company",
                "2284.SR": "Modern Mills Company",
                "2286.SR": "Fourth Milling Company",
                "2281.SR": "Tanmiah Food Company",
                "6001.SR": "حلواني إخوان",
                "6014.SR": "Alamar Foods Company",
                "6002.SR": "هرفي",
                "9559.SR": "Balady Poultry Company",
                "2288.SR": "Nofoth Food Products Company",
                "6016.SR": "Shatirah House Restaurant Co.",
                "6050.SR": "Saudi Fisheries Company",
            },
            "الاستثمار المتعدد": {
                "4280.SR": "المملكة القابضة",
                "2382.SR": "ADES Holding Company",
                "1111.SR": "مجموعة تداول السعودية",
                "4090.SR": "Taiba Investment Company",
                "6004.SR": "كاتيرين",
                "4007.SR": "Al Hammadi Holding Company",
                "2190.SR": "Sustained Infrastructure Holding Company",
                "4083.SR": "United International Holding Company",
                "4240.SR": "AFG International Company",
                "9535.SR": "Ladun Investment Company",
                "9601.SR": "Mohammed Hadi Al-Rasheed Company",
                "4080.SR": "Sinad Holding Company",
                "2140.SR": "Ayyan Investment Company",
                "1214.SR": "Al Hassan Ghazi Ibrahim Shaker Company",
                "9521.SR": "INMAR Company",
                "1324.SR": "Saleh Abdulaziz Al Rashed & Sons Co.",
                "4147.SR": "Consolidated Grunenfelder Saady Holding Company",
                "4180.SR": "Fitaihi Holding Group",
                "1820.SR": "BAAN Holding Group Company",
                "9560.SR": "Waja Company",
                "9542.SR": "Keir International Co.",
                "4130.SR": "Darb Saudi Investment Company",
                "4061.SR": "أنعام القابضة",
                "6020.SR": "Al Gassim Investment Holding Company",
                "9628.SR": "Lamasat Company",
                "3008.SR": "Al Kathiri Holding Company",
            },
            "النقل": {
                "4030.SR": "البحري",
                "4263.SR": "SAL Saudi Logistics Services Company",
                "4200.SR": "الدريس",
                "4264.SR": "طيران ناس",
                "4031.SR": "Saudi Ground Services Company",
                "4260.SR": "United International Transportation Company",
                "4050.SR": "Saudi Automotive Services Company",
                "4262.SR": "Lumi Rental Company",
                "4261.SR": "Theeb Rent A Car Company",
                "4040.SR": "Saudi Public Transport Company",
                "4110.SR": "باتك",
                "1832.SR": "Sadr Logistics Company",
            },
            "التأمين": {
                "8210.SR": "بوبا العربية",
                "8010.SR": "التعاونية",
                "8230.SR": "الراجحي تكافل",
                "8200.SR": "إعادة التأمين السعودية",
                "8030.SR": "The Mediterranean and Gulf Cooperative Insurance and Reinsurance Company | 2.26B",
                "8250.SR": "Gulf Insurance Group",
                "8060.SR": "والاء للتأمين التعاوني",
                "8070.SR": "Arabian Shield Cooperative Insurance Company",
                "8240.SR": "Chubb Arabia Cooperative Insurance Company",
                "8012.SR": "Aljazira Takaful Taawuni Company",
                "8120.SR": "Gulf Union Alahlia Cooperative Insurance Company",
                "8040.SR": "Mutakamela Insurance Company",
                "8300.SR": "Wataniya Insurance Company",
                "8280.SR": "Liva Insurance Company",
                "8020.SR": "Malath Cooperative Insurance Company",
                "8160.SR": "Arabia Insurance Cooperative Company",
            },
            "العقار": {
                "4325.SR": "Umm Al Qura for Development and Construction Company",
                "4300.SR": "دار الأركان",
                "4100.SR": "Makkah Construction and Development Company",
                "4250.SR": "Jabal Omar Development Company",
                "4220.SR": "إعمار الاقتصادية",
                "4321.SR": "Arabian Centres Company",
                "4020.SR": "إعمار الاقتصادية السعودية",
                "4322.SR": "Retal Urban Development Company",
                "4150.SR": "طيبة",
                "4310.SR": "Knowledge Economic City Company",
                "4327.SR": "Al Ramz Real Estate Company",
                "4326.SR": "Dar Al Majed Real Estate Company",
                "4323.SR": "Sumou Real Estate Company",
                "4320.SR": "Alandalus Property Company",
                "9610.SR": "First Avenue Real Estate Development Company",
                "9640.SR": "ASAS Makeen Real Estate Development and Investment Company",
                "4324.SR": "Banan Real Estate Company",
                "9634.SR": "Adeer Real Estate Company",
                "2130.SR": "Saudi Industrial Development Co.",
                "6090.SR": "Jazan Development and Investment Company",
                "6060.SR": "Ash-Sharqiyah Development Co.",
            },
            "التجزئة": {
                "4190.SR": "جرير",
                "4161.SR": "بن داود",
                "4003.SR": "إكسترا",
                "4001.SR": "العثيم",
                "4192.SR": "Al-Saif Stores for Development & Investment Company",
                "4193.SR": "Nice One Beauty Digital Marketing Company",
                "9649.SR": "Jamjoom Fashion Trading Company",
                "4191.SR": "Abdullah Saad Mohammed Abo Moati for Bookstores Company",
                "4008.SR": "Saudi Company for Hardware SACO",
                "4144.SR": "Raoom trading Company",
                "4265.SR": "Cherry Trading Company",
                "4194.SR": "Marketing Home Group Company for Trading Company",
                "4006.SR": "Saudi Marketing Company",
                "3007.SR": "Zahrat Al Waha For Trading Company",
                "4051.SR": "Baazeem Trading Company",
                "9510.SR": "National Building and Marketing Co.",
                "4070.SR": "Tihama for Advertising, Public Relations and Marketing Company",
                "9639.SR": "Anmat Technology for Trading Co.",
            },
            "الإعلام": {
                "4072.SR": "MBC",
                "4210.SR": "المجموعة السعودية للأبحاث والإعلام",
            },
            "التعليم": {
                "4291.SR": "National Company for Learning and Education",
                "6019.SR": "Almasar Alshamil Education Company JSC",
                "4292.SR": "Ataa Educational Company",
                "4290.SR": "Al Khaleej Training and Education Company",
                "9541.SR": "Academy of Learning Company",
            },
            "الفنادق والسياحة": {
                "1810.SR": "سيرا القابضة",
                "4170.SR": "Tourism Enterprise Company (Shams)",
            },
            "الخدمات المالية": {
                "4084.SR": "دراية المالية",
                "1183.SR": "SHL Finance Company",
                "4081.SR": "Nayifat Finance Company",
                "1182.SR": "Amlak International Finance Company",
                "4082.SR": "Morabaha Marina Financing Company",
                "9596.SR": "Quara Finance Company",
            },
            "الأسمنت": {
                "3020.SR": "أسمنت اليمامة",
                "3040.SR": "أسمنت القصيم",
                "3030.SR": "أسمنت السعودية",
                "3092.SR": "Riyadh Cement Company",
                "3050.SR": "أسمنت الجنوب",
                "3060.SR": "أسمنت ينبع",
                "3010.SR": "Arabian Cement Company",
                "3080.SR": "Eastern Province Cement Company",
                "3003.SR": "City Cement Company",
                "3004.SR": "Northern Region Cement Company",
                "3002.SR": "Najran Cement Company",
                "3005.SR": "Umm Al-Qura Cement Company",
                "3090.SR": "Tabuk Cement Company",
                "3091.SR": "Al Jouf Cement Company",
            },
            "الزراعة": {
                "6010.SR": "The National Agricultural Development Company",
                "6070.SR": "Al-Jouf Agricultural Development Co.",
                "2287.SR": "Arabian Company for Agricultural and Industrial Investment",
                "2100.SR": "Wafrah for Industry and Development Company",
            },
            "الترفيه والرياضة": {
                "1830.SR": "ليجاسي (ليجاسي للياقة)",
                "9590.SR": "Armah Sports Company",
                "6018.SR": "Sport Clubs Company",
            },
            "السلع الاستهلاكية المعمرة": {
                "4165.SR": "Al Majed for Oud Company",
                "4012.SR": "Thob Al Aseel Company",
                "4011.SR": "L'azurde Company for Jewelry",
            },
            "الخدمات التجارية": {
                "1831.SR": "Maharah for Human Resources Company",
                "7204.SR": "Perfect Presentation for Commercial Services Company",
                "1835.SR": "Tamkeen Human Resources Company",
                "9540.SR": "National Environmental Recycling Company",
                "7205.SR": "Dar AlBalad for Business Solutions Company",
                "9543.SR": "Saudi Networkers Services Company",
            },
            "الصناديق العقارية": {
                "4340.SR": "Al Rajhi REIT Fund",
                "4344.SR": "SEDCO Capital REIT Fund",
                "4330.SR": "Riyad REIT Fund",
                "4333.SR": "Taleem REIT Fund",
                "4336.SR": "Mulkia Gulf Real Estate REIT",
            },
            "الورق والتغليف": {
                "4270.SR": "Saudi Printing and Packaging Co.",
            },
        },
    },
    "us": {
        "label": "السوق الأمريكي",
        "currency": "$",
        "sectors": {
            "الصناعة": {
                "MMM": "3M",
                "AOS": "A. O. Smith",
                "ALLE": "Allegion",
                "AME": "Ametek",
                "ADP": "Automatic Data Processing",
                "AXON": "Axon Enterprise",
                "BA": "Boeing",
                "BR": "Broadridge Financial Solutions",
                "BLDR": "Builders FirstSource",
                "CHRW": "C.H. Robinson",
                "CARR": "Carrier Global",
                "CAT": "Caterpillar Inc.",
                "CTAS": "Cintas",
                "FIX": "Comfort Systems USA",
                "CPRT": "Copart",
                "CSX": "CSX Corporation",
                "CMI": "Cummins",
                "DE": "Deere & Company",
                "DAL": "Delta Air Lines",
                "DOV": "Dover Corporation",
                "ETN": "Eaton Corporation",
                "EME": "Emcor",
                "EMR": "Emerson Electric",
                "EFX": "Equifax",
                "EXPD": "Expeditors International",
                "FAST": "Fastenal",
                "FDX": "FedEx",
                "FTV": "Fortive",
                "GE": "GE Aerospace",
                "GEV": "GE Vernova",
                "GNRC": "Generac",
                "GD": "General Dynamics",
                "HON": "Honeywell",
                "HWM": "Howmet Aerospace",
                "HUBB": "Hubbell Incorporated",
                "HII": "Huntington Ingalls Industries",
                "IEX": "IDEX Corporation",
                "ITW": "Illinois Tool Works",
                "IR": "Ingersoll Rand",
                "JBHT": "J.B. Hunt",
                "J": "Jacobs Solutions",
                "JCI": "Johnson Controls",
                "LHX": "L3Harris",
                "LDOS": "Leidos",
                "LII": "Lennox International",
                "LMT": "Lockheed Martin",
                "MAS": "Masco",
                "NDSN": "Nordson Corporation",
                "NSC": "Norfolk Southern",
                "NOC": "Northrop Grumman",
                "ODFL": "Old Dominion",
                "OTIS": "Otis Worldwide",
                "PCAR": "Paccar",
                "PH": "Parker Hannifin",
                "PAYX": "Paychex",
                "PNR": "Pentair",
                "PWR": "Quanta Services",
                "RTX": "RTX Corporation",
                "RSG": "Republic Services",
                "ROK": "Rockwell Automation",
                "ROL": "Rollins, Inc.",
                "SNA": "Snap-on",
                "LUV": "Southwest Airlines",
                "SWK": "Stanley Black & Decker",
                "TXT": "Textron",
                "TT": "Trane Technologies",
                "TDG": "TransDigm Group",
                "UBER": "Uber",
                "UNP": "Union Pacific Corporation",
                "UAL": "United Airlines Holdings",
                "UPS": "United Parcel Service",
                "URI": "United Rentals",
                "VLTO": "Veralto",
                "VRSK": "Verisk Analytics",
                "VRT": "Vertiv",
                "GWW": "W. W. Grainger",
                "WAB": "Wabtec",
                "WM": "Waste Management",
                "XYL": "Xylem Inc.",
            },
            "الرعاية الصحية": {
                "ABT": "Abbott Laboratories",
                "ABBV": "AbbVie",
                "A": "Agilent Technologies",
                "ALGN": "Align Technology",
                "AMGN": "Amgen",
                "BAX": "Baxter International",
                "BDX": "Becton Dickinson",
                "TECH": "Bio-Techne",
                "BIIB": "Biogen",
                "BSX": "Boston Scientific",
                "BMY": "Bristol Myers Squibb",
                "CAH": "Cardinal Health",
                "COR": "Cencora",
                "CNC": "Centene Corporation",
                "CRL": "Charles River Laboratories",
                "CI": "Cigna",
                "COO": "Cooper Companies",
                "CVS": "CVS Health",
                "DHR": "Danaher Corporation",
                "DVA": "DaVita",
                "DXCM": "Dexcom",
                "EW": "Edwards Lifesciences",
                "ELV": "Elevance Health",
                "GEHC": "GE HealthCare",
                "GILD": "Gilead Sciences",
                "HCA": "HCA Healthcare",
                "HSIC": "Henry Schein",
                "HUM": "Humana",
                "IDXX": "Idexx Laboratories",
                "INCY": "Incyte",
                "PODD": "Insulet Corporation",
                "ISRG": "Intuitive Surgical",
                "IQV": "IQVIA",
                "JNJ": "Johnson & Johnson",
                "LH": "Labcorp",
                "LLY": "Lilly (Eli)",
                "MCK": "McKesson Corporation",
                "MDT": "Medtronic",
                "MRK": "Merck & Co.",
                "MTD": "Mettler Toledo",
                "MRNA": "Moderna",
                "PFE": "Pfizer",
                "DGX": "Quest Diagnostics",
                "REGN": "Regeneron Pharmaceuticals",
                "RMD": "ResMed",
                "RVTY": "Revvity",
                "SOLV": "Solventum",
                "STE": "Steris",
                "SYK": "Stryker Corporation",
                "TMO": "Thermo Fisher Scientific",
                "UNH": "UnitedHealth Group",
                "UHS": "Universal Health Services",
                "VEEV": "Veeva Systems",
                "VRTX": "Vertex Pharmaceuticals",
                "VTRS": "Viatris",
                "WAT": "Waters Corporation",
                "WST": "West Pharmaceutical Services",
                "ZBH": "Zimmer Biomet",
                "ZTS": "Zoetis",
            },
            "التقنية": {
                "ACN": "Accenture",
                "ADBE": "Adobe Inc.",
                "AMD": "Advanced Micro Devices",
                "AKAM": "Akamai Technologies",
                "APH": "Amphenol",
                "ADI": "Analog Devices",
                "AAPL": "Apple Inc.",
                "AMAT": "Applied Materials",
                "APP": "AppLovin",
                "ANET": "Arista Networks",
                "ADSK": "Autodesk",
                "AVGO": "Broadcom",
                "CDNS": "Cadence Design Systems",
                "CDW": "CDW Corporation",
                "CIEN": "Ciena",
                "CSCO": "Cisco",
                "CTSH": "Cognizant",
                "COHR": "Coherent Corp.",
                "GLW": "Corning Inc.",
                "CRWD": "CrowdStrike",
                "DDOG": "Datadog",
                "DELL": "Dell Technologies",
                "EPAM": "EPAM Systems",
                "FFIV": "F5, Inc.",
                "FICO": "Fair Isaac",
                "FSLR": "First Solar",
                "FTNT": "Fortinet",
                "IT": "Gartner",
                "GEN": "Gen Digital",
                "GDDY": "GoDaddy",
                "HPE": "Hewlett Packard Enterprise",
                "HPQ": "HP Inc.",
                "IBM": "IBM",
                "INTC": "Intel",
                "INTU": "Intuit",
                "JBL": "Jabil",
                "KEYS": "Keysight Technologies",
                "KLAC": "KLA Corporation",
                "LRCX": "Lam Research",
                "LITE": "Lumentum",
                "MCHP": "Microchip Technology",
                "MU": "Micron Technology",
                "MSFT": "Microsoft",
                "MPWR": "Monolithic Power Systems",
                "MSI": "Motorola Solutions",
                "NTAP": "NetApp",
                "NVDA": "Nvidia",
                "NXPI": "NXP Semiconductors",
                "ON": "ON Semiconductor",
                "ORCL": "Oracle Corporation",
                "PLTR": "Palantir Technologies",
                "PANW": "Palo Alto Networks",
                "PTC": "PTC Inc.",
                "QCOM": "Qualcomm",
                "Q": "Qnity Electronics",
                "ROP": "Roper Technologies",
                "CRM": "Salesforce",
                "SNDK": "Sandisk",
                "STX": "Seagate Technology",
                "NOW": "ServiceNow",
                "SWKS": "Skyworks Solutions",
                "SMCI": "Supermicro",
                "SNPS": "Synopsys",
                "TEL": "TE Connectivity",
                "TDY": "Teledyne Technologies",
                "TER": "Teradyne",
                "TXN": "Texas Instruments",
                "TRMB": "Trimble Inc.",
                "TYL": "Tyler Technologies",
                "VRSN": "Verisign",
                "WDC": "Western Digital",
                "WDAY": "Workday, Inc.",
                "ZBRA": "Zebra Technologies",
            },
            "المرافق": {
                "AES": "AES Corporation",
                "LNT": "Alliant Energy",
                "AEE": "Ameren",
                "AEP": "American Electric Power",
                "AWK": "American Water Works",
                "ATO": "Atmos Energy",
                "CNP": "CenterPoint Energy",
                "CMS": "CMS Energy",
                "ED": "Consolidated Edison",
                "CEG": "Constellation Energy",
                "D": "Dominion Energy",
                "DTE": "DTE Energy",
                "DUK": "Duke Energy",
                "EIX": "Edison International",
                "ETR": "Entergy",
                "EVRG": "Evergy",
                "ES": "Eversource Energy",
                "EXC": "Exelon",
                "FE": "FirstEnergy",
                "NEE": "NextEra Energy",
                "NI": "NiSource",
                "NRG": "NRG Energy",
                "PCG": "PG&E Corporation",
                "PNW": "Pinnacle West Capital",
                "PPL": "PPL Corporation",
                "PEG": "Public Service Enterprise Group",
                "SRE": "Sempra",
                "SO": "Southern Company",
                "VST": "Vistra Corp.",
                "WEC": "WEC Energy Group",
                "XEL": "Xcel Energy",
            },
            "الخدمات المالية": {
                "AFL": "Aflac",
                "ALL": "Allstate",
                "AXP": "American Express",
                "AIG": "American International Group",
                "AMP": "Ameriprise Financial",
                "AON": "Aon plc",
                "APO": "Apollo Global Management",
                "ACGL": "Arch Capital Group",
                "ARES": "Ares Management",
                "AJG": "Arthur J. Gallagher & Co.",
                "AIZ": "Assurant",
                "BAC": "Bank of America",
                "BRK-B": "Berkshire Hathaway",
                "BLK": "BlackRock",
                "BX": "Blackstone Inc.",
                "XYZ": "Block, Inc.",
                "BNY": "BNY Mellon",
                "BRO": "Brown & Brown",
                "COF": "Capital One",
                "CBOE": "Cboe Global Markets",
                "SCHW": "Charles Schwab Corporation",
                "CB": "Chubb Limited",
                "CINF": "Cincinnati Financial",
                "C": "Citigroup",
                "CFG": "Citizens Financial Group",
                "CME": "CME Group",
                "COIN": "Coinbase",
                "CPAY": "Corpay",
                "ERIE": "Erie Indemnity",
                "EG": "Everest Group",
                "FDS": "FactSet",
                "FIS": "Fidelity National Information Services",
                "FITB": "Fifth Third Bancorp",
                "FISV": "Fiserv",
                "BEN": "Franklin Resources",
                "GPN": "Global Payments",
                "GL": "Globe Life",
                "GS": "Goldman Sachs",
                "HIG": "Hartford",
                "HBAN": "Huntington Bancshares",
                "IBKR": "Interactive Brokers",
                "ICE": "Intercontinental Exchange",
                "IVZ": "Invesco",
                "JKHY": "Jack Henry & Associates",
                "JPM": "JPMorgan Chase",
                "KEY": "KeyCorp",
                "KKR": "KKR & Co.",
                "L": "Loews Corporation",
                "MTB": "M&T Bank",
                "MMC": "Marsh McLennan",
                "MA": "Mastercard",
                "MET": "MetLife",
                "MCO": "Moody's Corporation",
                "MS": "Morgan Stanley",
                "MSCI": "MSCI Inc.",
                "NDAQ": "Nasdaq, Inc.",
                "NTRS": "Northern Trust",
                "PYPL": "PayPal",
                "PNC": "PNC Financial Services",
                "PFG": "Principal Financial Group",
                "PGR": "Progressive Corporation",
                "PRU": "Prudential Financial",
                "RJF": "Raymond James Financial",
                "RF": "Regions Financial Corporation",
                "HOOD": "Robinhood Markets",
                "SPGI": "S&P Global",
                "STT": "State Street Corporation",
                "SYF": "Synchrony Financial",
                "TROW": "T. Rowe Price",
                "TRV": "Travelers Companies",
                "TFC": "Truist Financial",
                "USB": "U.S. Bancorp",
                "V": "Visa Inc.",
                "WRB": "W. R. Berkley Corporation",
                "WFC": "Wells Fargo",
                "WTW": "Willis Towers Watson",
            },
            "المواد الأساسية": {
                "APD": "Air Products",
                "ALB": "Albemarle Corporation",
                "AMCR": "Amcor",
                "AVY": "Avery Dennison",
                "BALL": "Ball Corporation",
                "CF": "CF Industries",
                "CTVA": "Corteva",
                "CRH": "CRH plc",
                "DOW": "Dow Inc.",
                "DD": "DuPont",
                "ECL": "Ecolab",
                "FCX": "Freeport-McMoRan",
                "IFF": "International Flavors & Fragrances",
                "IP": "International Paper",
                "LIN": "Linde plc",
                "LYB": "LyondellBasell",
                "MLM": "Martin Marietta Materials",
                "MOS": "Mosaic Company",
                "NEM": "Newmont",
                "NUE": "Nucor",
                "PKG": "Packaging Corporation of America",
                "PPG": "PPG Industries",
                "SHW": "Sherwin-Williams",
                "SW": "Smurfit Westrock",
                "STLD": "Steel Dynamics",
                "VMC": "Vulcan Materials Company",
            },
            "السلع الكمالية": {
                "ABNB": "Airbnb",
                "AMZN": "Amazon",
                "APTV": "Aptiv",
                "AZO": "AutoZone",
                "BBY": "Best Buy",
                "BKNG": "Booking Holdings",
                "CCL": "Carnival Corporation",
                "CVNA": "Carvana",
                "CMG": "Chipotle Mexican Grill",
                "DRI": "Darden Restaurants",
                "DECK": "Deckers Brands",
                "DPZ": "Domino's",
                "DASH": "DoorDash",
                "DHI": "D. R. Horton",
                "EBAY": "eBay Inc.",
                "EXPE": "Expedia Group",
                "F": "Ford Motor Company",
                "GRMN": "Garmin",
                "GM": "General Motors",
                "GPC": "Genuine Parts Company",
                "HAS": "Hasbro",
                "HLT": "Hilton Worldwide",
                "HD": "Home Depot",
                "LVS": "Las Vegas Sands",
                "LEN": "Lennar",
                "LOW": "Lowe's",
                "LULU": "Lululemon Athletica",
                "MAR": "Marriott International",
                "MCD": "McDonald's",
                "MGM": "MGM Resorts",
                "NKE": "Nike, Inc.",
                "NCLH": "Norwegian Cruise Line Holdings",
                "NVR": "NVR, Inc.",
                "ORLY": "O'Reilly Automotive",
                "POOL": "Pool Corporation",
                "PHM": "PulteGroup",
                "RL": "Ralph Lauren Corporation",
                "ROST": "Ross Stores",
                "RCL": "Royal Caribbean Group",
                "SBUX": "Starbucks",
                "TPR": "Tapestry, Inc.",
                "TSLA": "Tesla, Inc.",
                "TJX": "TJX Companies",
                "TSCO": "Tractor Supply",
                "ULTA": "Ulta Beauty",
                "WSM": "Williams-Sonoma, Inc.",
                "WYNN": "Wynn Resorts",
                "YUM": "Yum! Brands",
            },
            "العقار": {
                "ARE": "Alexandria Real Estate Equities",
                "AMT": "American Tower",
                "AVB": "AvalonBay Communities",
                "BXP": "BXP, Inc.",
                "CPT": "Camden Property Trust",
                "CBRE": "CBRE Group",
                "CSGP": "CoStar Group",
                "CCI": "Crown Castle",
                "DLR": "Digital Realty",
                "EQIX": "Equinix",
                "EQR": "Equity Residential",
                "ESS": "Essex Property Trust",
                "EXR": "Extra Space Storage",
                "FRT": "Federal Realty Investment Trust",
                "DOC": "Healthpeak Properties",
                "HST": "Host Hotels & Resorts",
                "INVH": "Invitation Homes",
                "IRM": "Iron Mountain",
                "KIM": "Kimco Realty",
                "MAA": "Mid-America Apartment Communities",
                "PLD": "Prologis",
                "PSA": "Public Storage",
                "O": "Realty Income",
                "REG": "Regency Centers",
                "SBAC": "SBA Communications",
                "SPG": "Simon Property Group",
                "UDR": "UDR, Inc.",
                "VTR": "Ventas",
                "VICI": "Vici Properties",
                "WELL": "Welltower",
                "WY": "Weyerhaeuser",
            },
            "الاتصالات والإعلام": {
                "GOOGL": "Alphabet Inc. (Class A)",
                "GOOG": "Alphabet Inc. (Class C)",
                "T": "AT&T",
                "CHTR": "Charter Communications",
                "CMCSA": "Comcast",
                "SATS": "EchoStar",
                "EA": "Electronic Arts",
                "FOXA": "Fox Corporation (Class A)",
                "FOX": "Fox Corporation (Class B)",
                "LYV": "Live Nation Entertainment",
                "META": "Meta Platforms",
                "NFLX": "Netflix",
                "NWSA": "News Corp (Class A)",
                "NWS": "News Corp (Class B)",
                "OMC": "Omnicom Group",
                "PSKY": "Paramount Skydance Corporation",
                "TMUS": "T-Mobile US",
                "TTWO": "Take-Two Interactive",
                "TKO": "TKO Group Holdings",
                "TTD": "Trade Desk",
                "VZ": "Verizon",
                "DIS": "Walt Disney Company",
                "WBD": "Warner Bros. Discovery",
            },
            "السلع الأساسية": {
                "MO": "Altria",
                "ADM": "Archer Daniels Midland",
                "BF-B": "Brown-Forman",
                "BG": "Bunge Global",
                "CPB": "Campbell's Company",
                "CASY": "Casey's",
                "CHD": "Church & Dwight",
                "CLX": "Clorox",
                "KO": "Coca-Cola Company",
                "CL": "Colgate-Palmolive",
                "CAG": "Conagra Brands",
                "STZ": "Constellation Brands",
                "COST": "Costco",
                "DG": "Dollar General",
                "DLTR": "Dollar Tree",
                "EL": "Estee Lauder Companies",
                "GIS": "General Mills",
                "HSY": "Hershey Company",
                "HRL": "Hormel Foods",
                "KVUE": "Kenvue",
                "KDP": "Keurig Dr Pepper",
                "KMB": "Kimberly-Clark",
                "KHC": "Kraft Heinz",
                "KR": "Kroger",
                "MKC": "McCormick & Company",
                "TAP": "Molson Coors Beverage Company",
                "MDLZ": "Mondelez International",
                "MNST": "Monster Beverage",
                "PEP": "PepsiCo",
                "PM": "Philip Morris International",
                "PG": "Procter & Gamble",
                "SJM": "J.M. Smucker Company",
                "SYY": "Sysco",
                "TGT": "Target Corporation",
                "TSN": "Tyson Foods",
                "WMT": "Walmart",
            },
            "الطاقة": {
                "APA": "APA Corporation",
                "BKR": "Baker Hughes",
                "CVX": "Chevron Corporation",
                "COP": "ConocoPhillips",
                "DVN": "Devon Energy",
                "FANG": "Diamondback Energy",
                "EOG": "EOG Resources",
                "EQT": "EQT Corporation",
                "EXE": "Expand Energy",
                "XOM": "ExxonMobil",
                "HAL": "Halliburton",
                "KMI": "Kinder Morgan",
                "MPC": "Marathon Petroleum",
                "OXY": "Occidental Petroleum",
                "OKE": "Oneok",
                "PSX": "Phillips 66",
                "SLB": "Schlumberger",
                "TRGP": "Targa Resources",
                "TPL": "Texas Pacific Land Corporation",
                "VLO": "Valero Energy",
                "WMB": "Williams Companies",
            },
        },
    },
}

OUTPUT_PATH = "data/data.json"


def compute_rsi(closes, period=14):
    delta = closes.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.rolling(period).mean()
    avg_loss = loss.rolling(period).mean()
    rs = avg_gain / avg_loss.replace(0, np.nan)
    rsi = 100 - (100 / (1 + rs))
    return float(rsi.iloc[-1]) if not np.isnan(rsi.iloc[-1]) else 50.0


def compute_obv_slope(closes, volumes, lookback=10):
    direction = np.sign(closes.diff().fillna(0))
    obv = (direction * volumes).cumsum()
    recent = obv.tail(lookback)
    if len(recent) < 2:
        return 0.0
    x = np.arange(len(recent))
    slope = np.polyfit(x, recent.values, 1)[0]
    norm = slope / (volumes.tail(lookback).mean() + 1e-9)
    return float(np.clip(norm * 100, -100, 100))


def market_price_status(market_key):
    now = datetime.datetime.utcnow()
    weekday = now.weekday()  # الاثنين=0 ... الأحد=6
    hour = now.hour + now.minute / 60

    if market_key == "sa":
        is_open = weekday in (6, 0, 1, 2, 3) and 7.0 <= hour <= 12.33
    elif market_key == "us":
        is_open = weekday in (0, 1, 2, 3, 4) and 13.5 <= hour <= 20.0
    else:
        is_open = False

    return "لحظي أثناء التداول" if is_open else "إغلاق رسمي (آخر جلسة مكتملة)"


def classify(accumulation_score, rsi):
    if accumulation_score >= 65 and rsi < 70:
        return "تجميع نشط"
    if accumulation_score <= 35 and rsi > 30:
        return "تصريف"
    if rsi >= 70:
        return "تشبع شرائي"
    if rsi <= 30:
        return "تشبع بيعي"
    return "محايد"


def analyze_ticker(symbol, name):
    try:
        hist = yf.Ticker(symbol).history(period="1y", interval="1d")
    except Exception as e:
        print(f"[خطأ] {symbol} ({name}): استثناء أثناء الجلب -> {e}")
        return None
    if hist is None or len(hist) < 30:
        return None

    closes = hist["Close"].ffill().bfill()
    volumes = hist["Volume"].fillna(0)

    price = float(closes.iloc[-1])
    prev_price = float(closes.iloc[-2])
    if math.isnan(price) or math.isnan(prev_price) or prev_price == 0:
        return None
    change_pct = ((price - prev_price) / prev_price) * 100

    rsi14 = compute_rsi(closes)
    avg_vol_20 = float(volumes.tail(20).mean())
    today_vol = float(volumes.iloc[-1])
    volume_ratio = (today_vol / avg_vol_20) if avg_vol_20 > 0 else 1.0
    obv_slope = compute_obv_slope(closes, volumes)

    support = float(closes.tail(20).min())
    resistance = float(closes.tail(20).max())
    week52_low = float(closes.min())
    week52_high = float(closes.max())

    proximity_to_support = max(0.0, 1 - ((price - support) / (resistance - support + 1e-9)))
    accumulation_score = float(np.clip(
        (obv_slope * 0.5) + (min(volume_ratio, 3) / 3 * 30) + (proximity_to_support * 20) + 50,
        0, 100
    ))
    classification = classify(accumulation_score, rsi14)

    atr = float((hist["High"].ffill().bfill() - hist["Low"].ffill().bfill()).tail(14).mean())
    stop_loss = round(support - atr * 0.5, 2)
    target1 = round(price + atr * 1.5, 2)
    target2 = round(price + atr * 3, 2)
    target3 = round(resistance, 2)

    row = {
        "code": symbol.replace(".SR", ""),
        "name": name,
        "price": round(price, 2),
        "change_pct": round(change_pct, 2),
        "rsi14": round(rsi14, 1),
        "volume_ratio": round(volume_ratio, 2),
        "accumulation_score": round(accumulation_score, 1),
        "classification": classification,
        "support": round(support, 2),
        "resistance": round(resistance, 2),
        "week52_low": round(week52_low, 2),
        "week52_high": round(week52_high, 2),
        "stop_loss": stop_loss,
        "target1": target1,
        "target2": target2,
        "target3": target3,
    }

    for key, value in row.items():
        if isinstance(value, float) and math.isnan(value):
            return None

    return row


def main():
    output = {"updated_at": datetime.datetime.utcnow().isoformat() + "Z", "markets": {}}

    for market_key, market in SECTORS.items():
        sectors_out = []
        for sector_name, tickers in market["sectors"].items():
            stocks = []
            for symbol, name in tickers.items():
                row = analyze_ticker(symbol, name)
                if row:
                    stocks.append(row)
            if stocks:
                sector_score = round(float(np.mean([s["accumulation_score"] for s in stocks])), 1)
                sectors_out.append({
                    "name": sector_name,
                    "score": sector_score,
                    "stocks": sorted(stocks, key=lambda s: s["accumulation_score"], reverse=True),
                })
        sectors_out.sort(key=lambda s: s["score"], reverse=True)
        output["markets"][market_key] = {
            "label": market["label"],
            "currency": market["currency"],
            "price_status": market_price_status(market_key),
            "sectors": sectors_out,
        }

    os.makedirs("data", exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    total = sum(len(s["stocks"]) for m in output["markets"].values() for s in m["sectors"])
    print(f"تم تحليل {total} سهم عبر {len(output['markets'])} سوق، وكتابتها إلى {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
